apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: astronomy-frontend-chaos
  namespace: litmus
spec:
  engineState: 'active'
  appinfo:
    appns: 'astronomy'
    applabel: 'app.kubernetes.io/name=frontend'
    appkind: 'deployment'
  chaosServiceAccount: litmus-admin
  experiments:
  - name: pod-delete
    spec:
      components:
        env:
        # Kill pods for 30 seconds
        - name: TOTAL_CHAOS_DURATION
          value: '30'
        - name: CHAOS_INTERVAL
          value: '10'
        - name: FORCE
          value: 'false'
