apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: frontend-cron-scaler
  namespace: astronomy
spec:
  scaleTargetRef:
    name: otel-demo-frontend
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: cron
    metadata:
      timezone: UTC
      start: "0 0 * * *"      # Always Active (Start of day)
      end: "23 59 * * *"      # End of day
      desiredReplicas: "5"    # FORCE SCALE TO 5
